### ISSUE TITLE
What's the purpose of u-sizeFillAlt?

### ISSUE THREAD

**Issue by oleersoy** [suitcss/utils-size#25]
I pasted the code below for reference.  When should u-sizeFillAlt be used?  From reading the docs u-sizeFillAlt looks like a possibly inferior form of u-sizeFill...

    /**
     * Make an element fill the remaining space.
     * N.B. This will hide overflow.
     */

    .u-sizeFill {
      display: block !important;
      overflow: hidden !important;
      width: auto !important;
    }

    /**
     * An alternative method to make an element fill the remaining space.
     * N.B. Do not use if child elements might be wider than the remaining space.
     * In Chrome, Safari, and Firefox it results in undesired layout.
     */

    .u-sizeFillAlt {
      display: table-cell !important;
      max-width: 100% !important;
      width: 10000px !important;
    }

**Comment by AntonTrollback** [comment]
I have been using it when overflow should be preserved

**Comment by necolas** [comment]
Yes that's what it's for, although not clearly documented as such. I haven't been using these sizing utils much since adopting flexbox.

**Comment by oleersoy** [comment]
Could these be renamed to reflect their function more accurately.  For example `u-fillHide` and `u-fillShow`.

**Comment by giuseppeg** [comment]
They are a copies of `u-nbfc` and `u-nbgcAlt` http://git.io/vZrKQ

**Comment by oleersoy** [comment]
So `u-sizeFillAlt` is for when overflow should be preserved?  This seems contrary to "N.B. Do not use if child elements might be wider than the remaining space."...

The main reason I'm going through all the tests, docs, etc. is because I'm trying to understand when I would use certain utilities / components. etc.  Right now it seems that if I want it not to wrap and display all of the content on one line, then I would use `u-sizeFillAlt`.  

Is this the only way (Popular in the sense that `u-cf` is popular and generally understood and accepted) to do this?  Is just get the feeling that there should be a more lightweight way to accomplish this, possibly by combining utilities, that would be more descriptive and easy to understand?  Personally I have a much easier time reading markup if when the utilities are focused.  For example:

- `u-floatLeft`: Float it left
- `u-hideOverflow`:  Hides the overflow
- `u-showOverflow`: Keeps the content on one line and causes a scrollbar to appear if the content exceeds container width.
- `u-expandToFullWidth`: Expands an inline element to fit the width of the container, possibly by changing display to block.

Some of the above are jjust hypothetical examples of the types of utilities are easy to visually unit test and understand.  We could then combine them to attain the type of effect that we are seeking with `u-sizeFill` and `u-sizeFillAlt`.  I'd love to see these deprecated and replaced with a refactoring that is then moved into utils-layout.  The result should be something that keeps the knowledge of how to achieve what their original goal is / was (Once the goal is obvious and clear through a unit test - I'll write it - might need some help though), but is easier to breakdown because the tests show the purpose more clearly by setting up the testing context such that the purpose is obvious.  For example `u-sizeFillAlt` has no overflow in the test...

**Comment by oleersoy** [comment]
I'm going to disclaim first.  I'm by no means a CSS guru.  Trying to get better :).  So if I'm simply confused, please let me know.

I changed the test for both:
-  `.u-sizeFit / .u-sizeFill`
- `.u-sizeFit / .u-sizeFillAlt` by adding:

 `Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum content` 

such that the content wraps.  Both tests look exactly the same (The content does display in entirely and it wraps)...which...IIUC...should not be the case?

**Comment by giuseppeg** [comment]
@oleersoy this [article](https://web.archive.org/web/20140409035406/http://colinaarts.com/articles/the-magic-of-overflow-hidden) should clarify what are these utilities for, why we use `overflow: hidden` and why we have an alternative.

fwiw utilities should be atomic and don't have dependencies imho.
I am going to close this issue, feel free to give some love (improve) to the docs/comments and submit a PR!  :)

**Comment by oleersoy** [comment]
Can we just keep these open until the love is in place :)?  It's easier to keep them on the radar that way :).

**Comment by oleersoy** [comment]
BTW - Thanks for the article.  It's making a lot more sense now :+1: 

Would still be great to have the issue open though so it stays on my radar.

**Comment by giuseppeg** [comment]
@oleersoy there is a [comment](https://github.com/suitcss/utils-size/blob/master/lib/size.css#L25) on `u-sizeFill` already that explains the side effects of the main method

**Comment by necolas** [comment]
yeah probably a good idea to remove the size utilities that can be replaced with flexbox

**Comment by oleersoy** [comment]
Cool!  Does this mean that we are clear to go on a pure flexbox Grid?  

@giuseppeg I understand there is a comment, but it's tough to to distill...As the article explains the overflow concept is used as a hack to achieve something completely different from what overflow values were intended to do.  Also if we look at the comment and then the test..it's still like `huh`?  It's hard to reason about this and overall the naming of the utilities should be semantic, and currently they are not.  In order to upgrade the utility to flexbox, we have to have a precise understanding of the behaviour previously through testing, such that the flexbox utility provides the same unit tested behavior...Or perhaps something better, but the difference should be explained to current users, such that they are not caught off guard on upgrades.  If this is obvious, then it should be implemented, and then the issue closed.

Also you mentioned that they are copies of `u-nbfc` and `u-nbgcAlt` which probably should be included in the thinking about how to go about the redesign.  Also is it a good idea to have copies?

**Comment by necolas** [comment]
I don't think needs to be that complicated. We can drop the fit/fill size utilities entirely from this package.

**Comment by oleersoy** [comment]
Shouldn't the release note / change history say something like:

__________, __________, ___________ have been deprecated.  Use ______________, ____________, ____________ instead?

Also what about the copies?
