### ISSUE TITLE
Add utility for width: 100%

### ISSUE THREAD

**Issue by saralohr** [suitcss/utils-size#35]
We at [Cloud Four](http://www.cloudfour.com) are big fans of SUITCSS. We use it as a base for most of our projects. Thank you for providing such a great resource!

One thing I've wanted a few times is a responsive sizing utility for `width: 100%` that does not also add `display: block` like `u-sizeFull` does. Maybe this could be added to the sizing utilities as something like `u-size1of1`?

**Comment by timkelty** [comment]
Seems reasonable. Can you include a use-case where the added `display: block` isn't what you want?

Perhaps the bigger question is: Do we need `display: block` on `u-sizeFull` at all? @giuseppeg @simonsmith

**Comment by saralohr** [comment]
> Can you include a use-case where the added display: block isn't what you want?

For example, a containing element has the class `u-flex` and also has some sizing utilities applied at different breakpoints. If at any of these breakpoints this element needs to be full width, `u-sizeFull` can't be used because it applies `display: block` and overrides the `display: flex` from `u-flex`.

> Perhaps the bigger question is: Do we need display: block on u-sizeFull at all?

I was wondering this too, but thought it might have some regression issues if in some case (though I can't think of what this is) the `display: block` was needed.

**Comment by timkelty** [comment]
I think my vote would be to drop the `display: block`.
I added some tests for your example: https://github.com/suitcss/utils-size/tree/sizeFull-with-flex

I also added a test for the `box-sizing: border-box` bit that was there too.

**Comment by timkelty** [comment]
@saralohr not a great solution, but wouldn't your case also be sidestepped by including `suitcss-utils-flex` _after_ `suitcss-utils-size`?

**Comment by saralohr** [comment]
@timkelty That would work, but we tend to keep our includes alphabetical and try to avoid any fragile dependencies. We've come to rely pretty heavily on utility classes with a single purpose for this reason. I think this is one of the few that does more than one thing, and interestingly, it's the only one we've had issues with. I'm in support of removing `display: block`.

**Comment by timkelty** [comment]
@saralohr Yep, makes sense.

**Comment by simonsmith** [comment]
I believe `display: block` was added so that if `sizeFull` was added to an `inline` element it would behave as expected. I would agree that `sizeFull` could just be `width: 100%` and leave the other properties to be handled elsewhere. We could potentially remove `border-box` as well.

**Comment by giuseppeg** [comment]
<blockquote>I believe display: block was added so that if sizeFull was added to an inline element it would behave as expected.</blockquote>
True, if we decide to remove `display: block` we should release a major version.

How bad would it be to keep `display: block` but make it weak i.e. remove `!important`? This way `u-flex` would be able to override the `display` prop but an `inline` element without `display` utils would still be block-level.

**Comment by simonsmith** [comment]
I think that would work but could be confusing, we could document it clearly though. I wonder if assuming `display: block` could also mess with other display types, such as putting the class on a list item and overriding `display: list-item` for example.

**Comment by giuseppeg** [comment]
yes I agree. Let's kill it with fire 🔥 and release `2.0.0`

**Comment by simonsmith** [comment]
@saralohr Published in [2.0.0](https://github.com/suitcss/utils-size/releases/tag/2.0.0)

**Comment by saralohr** [comment]
Awesome, thank you!
